### PR TITLE
support change ping url

### PR DESCRIPTION
**Pull request by ryunhe**

### CODE REVIEW

**Comment by pwittchen** [comment]
Thanks for this PR. Adding possibility to set this URL is good idea, but I would prefer to set it during object creation in a constructor or via builder to keep initial settings in one place without necessity to edit AndroidManifest.

**Comment by ryunhe** [comment]
i think that use builder is more better, set it in constructor just quick work-around, expect more elegant way.

**Comment by pwittchen** [comment]
Now, it's better. I've added some comments to your code. You can take a look on that and consider update. When everything will be fine, I can merge it.

**Comment by pwittchen** [comment]
When you will be done with your changes, you can squash your commits in this PR into one.
You can use: http://rebaseandsqua.sh/ website.

**Comment by ryunhe** [comment]
all done, plz :)

**Comment by pwittchen** [comment]
Thanks! I'm merging it. Later, I'll probably do some refactoring and add possibility to change `pingUrl` via fluent interface (builder) as it's optional parameter.

**Pull request merged**
