### PR TITLE
changing implementation of the OnlineChecker

### LINKED ISSUE #111: OnlineCheckerImpl does not check for internet connectivity
The OnlineCheckerImpl only checks if there is a network connection available (packets can be sent) but not whether it is connected to the greater internet.

As described in this stackoverflow:
http://stackoverflow.com/questions/6493517/detect-if-android-device-has-internet-connection

A decent way to do this would be checking if a host is reachable with a small timeout at a regular interval:
http://stackoverflow.com/questions/8919083/checking-host-reachability-availability-in-android

### PR DESCRIPTION
**Pull request by pwittchen**
Fixes #111 and #112.

### CODE REVIEW

**Comment by joielechong** [comment]
Thank you very much :+1: . This work with me. But could be not working in mainland China cause google is blocked there https://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China.

**Comment by pwittchen** [comment]
Ok. Thanks for the info I'll add a short update, which will allow for customizing host, port, and timeout.

**Comment by pwittchen** [comment]
New task is created in #119.

**Comment by pwittchen** [comment]
I've added new functionality for customizing ping parameters. You can check the documentation here: https://github.com/pwittchen/NetworkEvents#customizing-ping-parameters. It will be available in the next release.

**Comment by joielechong** [comment]
Thank your very much for your kind works :+1: :+1: :+1:

**Pull request merged**
